parameters:
    pagination.twig.extension.class: Mindy\Bundle\PaginationBundle\Twig\PaginationExtension
    pagination.factory.class: Mindy\Pagination\PaginationFactory
    pagination.handler.request.class: Mindy\Pagination\Handler\RequestPaginationHandler
    pagination.data_source.array.class: Mindy\Pagination\DataSource\ArrayDataSource
    pagination.data_source.query_set.class: Mindy\Pagination\DataSource\QuerySetDataSource

services:
    pagination.data_source.array:
        class: '%pagination.data_source.array.class%'
        public: true
        tags: ['pagination.data_source']
    Mindy\Pagination\DataSource\ArrayDataSource: '@pagination.data_source.array'

    pagination.data_source.query_set:
        class: '%pagination.data_source.query_set.class%'
        public: true
        tags: ['pagination.data_source']
    Mindy\Pagination\DataSource\QuerySetDataSource: '@pagination.data_source.query_set'

    pagination.handler.request:
        class: '%pagination.handler.request.class%'
        public: true
        arguments: ['@request_stack', '@router']
    Mindy\Pagination\Handler\RequestPaginationHandler: '@pagination.handler.request'

    pagination.factory:
        class: '%pagination.factory.class%'
        public: true
    Mindy\Pagination\PaginationFactory: '@pagination.factory'

    pagination.twig.extension:
        class: '%pagination.twig.extension.class%'
        public: false
        arguments: ['@twig']
        tags:
            - { name: 'twig.extension' }
